# Generated by Django 4.1.7 on 2023-05-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepair',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
